services:
  mysql:
    image : mysql:8.4
    restart : unless-stopped
    ports : ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD : projectteam2@@
      MYSQL_DATABASE : secondary_battery_db
      MYSQL_USER : root2
      MYSQL_PASSWORD : projectteam2@
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro

  opcua-server:
    build:
      context : .
      dockerfile : opcua-server/Dockerfile
    container_name : opcua-server
    hostname : opcua-server
    env_file : ./config.env
    restart : unless-stopped
    ports : ["4840:4840"]
    depends_on : [mysql]

  opcua-bridge:
    build:
      context: .
      dockerfile : opcua-bridge/Dockerfile
    container_name : opcua-bridge
    env_file : ./config.env
    restart : unless-stopped
    depends_on:
      - mysql
      - opcua-server
      

  plc-voltage:
    build:
      context: .
      dockerfile : plc-voltage/Dockerfile
    container_name : plc-voltage
    env_file : config.env
    restart : unless-stopped
    depends_on:
      - opcua-server

  vision1-writer:
    build:
      context : .
      dockerfile : vision1/Dockerfile
    container_name : vision1-writer
    env_file : ./config.env
    depends_on:
      - opcua-server
    restart : unless-stopped

  vision2-writer:
    build:
     context : .
     dockerfile : vision2/Dockerfile
    container_name : vision2-writer
    env_file : ./config.env
    depends_on:
      - opcua-server
    restart : unless-stopped

volumes:
  db_data : {}